### PR TITLE
Prepend App base path to the theme path

### PR DESCRIPTION
**Pull request by JeyKeu**

### CODE REVIEW

**Comment by joshbrw** [comment]
What is the purpose of this? What issue does it solve?

**Comment by JeyKeu** [comment]
I'm using the latest version of Laravel (5.2.35).
I have my themes directory under `resources` like this:
 `resources/themes`

In the `AuthServiceProvicer.php` I tell `Stylist` to register the theme path:

```php
Stylist::registerPath('resources/themes/mytheme', true);
```

In my case it doesn't work and throws:

`theme.json file does not exist at [].`

To make it work, I have to change the path to :

`'../resources/themes/mytheme'`

from:

`'resources/themes/mytheme'`

and when I do this the app works but  `artisan` throws the same error.

so this PR makes sure the path works always.

Please correct me if I'm entering the theme path incorrectly.

**Comment by joshbrw** [comment]
@JeyKeu I'd recommend doing:

```
Stylist::registerPath(app_path('resources/themes/mytheme'), true);
```

**Comment by JeyKeu** [comment]
it's `base_path`

**Comment by joshbrw** [comment]
I know it's base path, I edited my comment.

I believe you're meant to pass the absolute path to Stylist - it's an intended part of the design. If this PR were to be accepted, it'd likely break a lot of packages that use Stylist.

**Comment by JeyKeu** [comment]
Ok, I agree. Closing...

**Comment by kirkbushell** [comment]
Thanks for the discussion, lads. @joshbrw is indeed correct - it would break other packages :)

**Comment by joshbrw** [comment]
No worries @kirkbushell - I'm here to help, not just criticise ;)

**Pull request closed without merging**
