### PR TITLE
Make info logging of current theme on page load configurable

### PR DESCRIPTION
**Pull request by joshbrw**

### CODE REVIEW

**Comment by nWidart** [comment]
+1, my logs are getting flooded by this information, that's not really needed in production.

**Comment by joshbrw** [comment]
@nWidart not sure about the whole `app.debug` thing.. I have my app set into debug for development yet I don't want these messages in my log files

**Comment by nWidart** [comment]
That's why you can overwrite it, like it's explained in the debugbar config. It defaults to app.debug, but, you can overwrite it.

**Comment by kirkbushell** [comment]
I have one question:

Is there an issue with the log information being shown in your logs?

**Comment by joshbrw** [comment]
@kirkbushell The issue is that when testing a site I'm getting hundreds of lines of basically useless info come into my log messages, which is getting in the way of useful log messages. I don't see there being a problem with this pull request being merged, as it still enables the logs by default.

**Comment by kirkbushell** [comment]
@joshbrw I like to understand the context first. I'm also not a fan of changing what would otherwise be default functionality. 

You say you'er getting hundreds of lines of log messages. Is this per request, or over the lifespan of many requests? If you're debugging a particular request, usually you go to the end of the file and work with the request you just had issues with. In this case, I usually end up wiping my logs and doing it then, and in our application we have about 50 lines of logging per request, which very quickly adds up over days, particularly on production servers that are seeing thousands of requests per day.

That said, I do not feel that the requirement is that much of an issue, and I'd much rather have verbose logs in all environments, than have conditions that challenge whether they're available or not.

There's no problem with merging the pull request per se, but it should be noted also whether or not said author thinks it's actually worth including.

Now, if there's a bug here that's causing a lot of unnecessary logging, then we can discuss further.

**Comment by joshbrw** [comment]
@kirkbushell If you can't understand why some people would want to enable and disable different parts of software then I can't help you.

**Comment by kirkbushell** [comment]
@joshbrw 

1. I wasn't asking for help, I was asking for clarification
2. There's no need to be snide when I was really quite nice and informed in my response.

**Comment by joshbrw** [comment]
I do not understand why you don't want to make open source software more customisable and configurable for the end user. This is a matter of personal preference. You're correct in the fact that it's not a **necessary** part of the codebase, but I do not understand why you are so against personal preference.

**Comment by kirkbushell** [comment]
Who said I was against personal preference? Can you follow a conversation?

Please re-read the questions I had, and either respond to them in kind, or leave the issue be.

When writing a package, there is more to include that just your own point of view. Every idea and pull request that comes in, I try and first fully understand the problem, decided whether it's an issue worth including, and then decide whether it's the right move for the package.

**Comment by kirkbushell** [comment]
I am still deciding wether or not I want to include such a change. Your rather abrupt and rude response led me to close the issue.

**Comment by joshbrw** [comment]
Which I would completely understand if it was anything more than a configuration option to turn off what is a rather pointless log message. You are welcome to keep the issue closed, as this change can be done on a fork.

**Comment by kirkbushell** [comment]
Okay so just to be clear, you're not willing to address the questions I asked at all?

**Comment by joshbrw** [comment]
I have explained the reason for this pull request, the reason is that I find the info messages annoying and useless (only useful for the edge case where you want to check what theme you're using), so adding the ability to disable it to stop it from flooding your log files is useful. It's nothing to do with "you should clear your log files X often" or "it's only once per request, you can look past it to see other logs", it's the simple fact that I personally find it a pointless message and would like to disable it.

**Comment by kirkbushell** [comment]
My question was regarding whether it was actually creating a problem. Imho, personal preference isn't a good enough reason to avoid good practice. It actually worries me that the only logs you're seeing - are from Stylist :)

**Comment by joshbrw** [comment]
That's quite an ignorant remark, as I stated in my previous comment that you can 'look part it to see other logs'. On all Operating Systems you can change a Desktop Wallpaper, it's not necessarily a "problem" if you can't, but it's a preference.

**Comment by kirkbushell** [comment]
What do you mean you can't look past it?

**Comment by joshbrw** [comment]
I said you can look past it, as in you can ignore it.

I was never solving a problem, I was trying to make an inconvenience for me a configurable option. Your response to it has disappointed me. Deleting the branch.

**Comment by kirkbushell** [comment]
Ah my apologies, I misunderstood.

Unfortunately I can't make everyone happy. I tend to favour convention over configuration where necessary.

**Comment by joshbrw** [comment]
I didn't know it was convention to log useless information, but ok.

**Comment by joshbrw** [comment]
I imagine you are still unwilling to allow the info logging to be configurable? If so I will fork and maintain my own version, but I am still very disappointed.

**Comment by kirkbushell** [comment]
I've decided to remove it completely, just haven't gotten around to it.

**Comment by joshbrw** [comment]
Perfect. I can submit a PR if that makes your life easier?

**Comment by kirkbushell** [comment]
If you wouldn't mind, that'd be great. Just remove it completely and I'll merge it in.

**Comment by joshbrw** [comment]
Done in PR

**Comment by kirkbushell** [comment]
Thanks @joshbrw, merged.

**Pull request closed without merging**
