### PR TITLE
Use prependLocation() instead of addLocation() to allow overriding theme after boot

### PR DESCRIPTION
**Pull request by darron1217**
Related to #35

### CODE REVIEW

**Comment by darron1217** [comment]
@kirkbushell Ping
Is this package not maintaining anymore?

**Comment by kirkbushell** [comment]
@darron1217 it is, just a bit busy is all.

Thanks for this, will test, merge then release.

**Comment by darron1217** [comment]
@kirkbushell Okay
Anyway, thanks for all the works you did 👍 
I'll look forward to be merged :)

**Comment by darron1217** [comment]
@kirkbushell Ping
I'm sorry for calling you again, but it's really simple PR...
Can you check it for a second?

**Comment by darron1217** [comment]
@kirkbushell Ping

**Comment by kirkbushell** [comment]
Thanks @darron1217 . Apologies, lots going on atm - I'll get to this tonight. Thanks again.

**Comment by darron1217** [comment]
Was there any problem on this PR?

**Comment by kirkbushell** [comment]
@darron1217 yes. Tests fail. prependLocation doesn't even seem like it's available.

**Comment by darron1217** [comment]
Okay.. I found the reason

https://laravel.com/api/5.4/Illuminate/View/FileViewFinder.html#method_prependLocation

This method is available from version 5.4

**Comment by kirkbushell** [comment]
Yeah, I tried a few different versions but cannot update to that version just yet. 5.4 is a long way from 5.0, which is where this package was sitting. I've brought it up to 5.1, as I believe that's an LTS release, and I'll release another update for 5.4 and above in a separate version chain so you can use it right away.

**Comment by darron1217** [comment]
@kirkbushell Okay then
How about checking out current master as branch `laravel-5.1` and start developing which is based on 5.4?

**Comment by kirkbushell** [comment]
Yup, I'll do exactly that but it will need to wait until later tonight. Thanks for being patient :)

**Comment by darron1217** [comment]
Anyway, I realized that laravel 5.5 is LTS (Also php version constraint has changed to 7 on this version)
So let's skip 5.4 and go straight to 5.5 support :)

**Comment by kirkbushell** [comment]
Yup, sounds good to me :)

**Pull request merged**
