### PR TITLE
make stylist work from subfolder

### PR DESCRIPTION
**Pull request by tk-s**
I think its not a good idea, to hardcode "/" as the public base_path (since then, working in a subfolder eg. dev.server/folder wont work.)
Changed to url() and it works like expected.

### CODE REVIEW

**Comment by nWidart** [comment]
:+1:

**Comment by tk-s** [comment]
thanks @nWidart i updated the TestCase too

**Comment by nWidart** [comment]
Awesome. 

@kirkbushell Tests (or better travis) fail(s) in 5.6 and 7, because of composer timeout.

**Comment by kirkbushell** [comment]
I will not change to this to a URL, as this means making external requests from the webserver which will not be supported on all webhosts. Base path should be set to the application path within a laravel application.

**Comment by kirkbushell** [comment]
My apologies, I actually misunderstood this PR with my previous comment.

@nWidart the composer timeout is due to some settings I'm having issues with on Travis.

**Comment by nWidart** [comment]
Oh really ? I'm having this timeout thing *constantly* on AsgardCms packages, super annoying :disappointed: . [They did acknowledge it](https://twitter.com/travisci/status/613116583397982209), but no more info..

**Comment by kirkbushell** [comment]
Providing a github oauth token is meant to get around it.

**Comment by nWidart** [comment]
any update?

**Comment by nWidart** [comment]
@kirkbushell multiple people reporting this issue on AsgardCms slack channel. Would be nice you can you click the 'merge' button.

**Comment by nWidart** [comment]
Thanks. :)

On Friday, July 10, 2015, Kirk Bushell <notifications@github.com> wrote:

> Merged #17 <https://github.com/floatingpointsoftware/stylist/pull/17>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/floatingpointsoftware/stylist/pull/17#event-352611911>
> .
>


-- 


Nicolas Widart
www.nicolaswidart.com

**Pull request merged**
