### PR TITLE
Add touch function to change last modification of the published theme…

### PR DESCRIPTION
**Pull request by mahmutbayri**
…. After getting the modification time of the theme using filemtime function (http://php.net/manual/tr/function.filemtime.php#32728), it can be using cache busting for the assets (js, css, img) of the theme. It is not best way for versioning but It is faster way and works.

### CODE REVIEW

**Comment by kirkbushell** [comment]
We can do cache busting based on the modified time of the file without having to manually touch it itself. Maybe we should have a further discussion about cache busting in general?

**Comment by mahmutbayri** [comment]
Gettting filemtime for each file can be slower. When i update the theme if i touch a folder, a new filemtime is generated, and it is ready a cache busting for all css, js.

Now, i generate my assets via gulp task runner, and it also create a file which is called build.txt  for each generation, then i use filemtime value of build.txt as cache busting.

Adding touch function to stylist might be usefull.

Thanks.

**Comment by kirkbushell** [comment]
@mahmutbayri okay you've sold me on it - but there are some build issues. If you'd like to address those, then I'll merge this in today :)

**Comment by kirkbushell** [comment]
@mahmutbayri I'll be closing this as there's no activity. If you want to continue on this please open a new PR.

**Pull request closed without merging**
