### PR TITLE
Fix arguments call in publish command

### PR DESCRIPTION
**Pull request by patrickbrouwers**
Your latest change broke the assets publishing.

`$this->argument()` returns `stylist:publish` instead of the given arguments.

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Note that something like `stylist:publish ThemeName` throws an `Too many arguments.` exception. I think this is because you don't tell the Command it should except arguments?

**Comment by kirkbushell** [comment]
getArguments only returns the arguments defined by the command, not the arguments themselves (that's what argument is meant to do). However, I've probably got it setup wrong, as you said. Will fix that up now.

**Comment by patrickbrouwers** [comment]
I think you'll have to tell the method which argument you want. 

`$this->argument('name');`

And define the name argument in `public function getArguments()`

**Comment by kirkbushell** [comment]
The problem is I want variable arguments - n number of arguments for the themes you want to publish.

**Pull request closed without merging**
