### PR TITLE
Typehint the Collective Html class

### PR DESCRIPTION
**Pull request by nWidart**

### CODE REVIEW

**Comment by nWidart** [comment]
Can you hold one a bit before merging it ? 
I need to send a PR to another package that still uses `Illuminate\Html` :disappointed:

**Comment by nWidart** [comment]
Can be merged now if you want.
Or I can send another PR that removes the typehint.

**Comment by mikedugan** [comment]
@nWidart is this PR redundant with #10 ?

**Comment by nWidart** [comment]
It's one or the other. I'd go with #10 , at least until one package becomes mainstream.

**Pull request closed without merging**
