### PR TITLE
Use prependLocation() instead of addLocation()

### PR DESCRIPTION
**Pull request by darron1217**
Finally solving issue #35

### CODE REVIEW

**Comment by darron1217** [comment]
@kirkbushell We're on 5.5 now :)

**Comment by darron1217** [comment]
@kirkbushell Ping
It's quite significant issue for me...

**Comment by kirkbushell** [comment]
@darron1217 apologies, been extremely busy with work. You know you can setup your own repositories right, while waiting? You can set your application to use your own repository until I can get this going. I still have a bit of work to do on this.

**Comment by darron1217** [comment]
Surely I know how to fork it (and know how to upload it on composer)

But this package is dependancy of CMS Platform I use ([AsgardCMS](https://asgardcms.com/)) 
https://github.com/AsgardCms/Platform/blob/7a91d62493ef564ca2fd7659319f6c680b131875/Modules/Core/composer.json#L30

I'm sorry to keep pushing you 😂
Just take a look when you have time.

Thanks in every way :)

**Comment by kirkbushell** [comment]
@darron1217 Ah. What you can do is specify where the repository is installed from, regardless of dependency. However, fair point. I'll really try and get to it tonight - sorry again.

**Comment by darron1217** [comment]
@kirkbushell  Hello, this is reminder :)

**Pull request merged**
