### PR TITLE
Remove the HtmlBuilder typehint completely.

### PR DESCRIPTION
**Pull request by nWidart**
Remove the HtmlBuilder typehint completely. 
This might be better, at least until there's only one of the 2 packages left.

### CODE REVIEW

**Comment by nWidart** [comment]
Hm don't know, @kirkbushell will be able to tell you.

**Comment by mikedugan** [comment]
Righteo, I'll leave this open and he can handle it whenever

**Comment by kirkbushell** [comment]
@mikedugan that's not a bad idea, I think I'll do that. I'll add an interface and then add an implementation for laravelcollective/html

**Comment by nWidart** [comment]
:+1: Good idea.

Could this be merged in the mean time ? (just so that it stays usable) :smile:

**Comment by kirkbushell** [comment]
Yup, we'll merge for now - but you'll need to run off master.

**Comment by kirkbushell** [comment]
Hmmm, build seems to be quite broken. Will sort out soon.

**Comment by nWidart** [comment]
Yeah I never saw the build green :P

**Comment by mikedugan** [comment]
I think Kirk gets a rise out of breaking travis :P

-- 
Mike Dugan
mike@dugan.io
http://dugan.io

On March 21, 2015 at 1:17:20 PM, Nicolas Widart (notifications@github.com) wrote:

Yeah I never saw the build green :P

**Comment by nWidart** [comment]
Whenever you're ready.. :stuck_out_tongue:

**Comment by kirkbushell** [comment]
Sorry @nWidart will get to it when I can.

**Comment by nWidart** [comment]
Okay. If you want me to add something to the PR to make your work easier let me know. :smiley:

**Pull request closed without merging**
